Repository ihhub/penguinV, pull requests merged in 2019-06, with the labels that each got.

#479 Issue 469: Merging CUDA and Qt Travis jobs
  .travis.yml
  script/travis/install_qt5.sh
Labels: Travis-CI, script

#481 Add ConvertTo16Bit() function by AVX
  src/image_function_simd.cpp
  test/unit_tests/unit_test_image_function.cpp
Labels: avx, core, enhancement

#474 Change bitmap operation example into file operation example
  examples/CMakeLists.txt
  examples/bitmap_operation/CMakeLists.txt
  examples/bitmap_operation/example_bitmap_operation.cpp
  examples/bitmap_operation/makefile
  examples/file_operation/CMakeLists.txt
  examples/file_operation/README.md
  examples/file_operation/example_file_operation.cpp
  examples/file_operation/example_file_operation.vcxproj
  examples/file_operation/makefile
  src/file/file_image.cpp
  src/file/png_image.cpp
Labels: enhancement

#484 Memory allocator implementation for CPU
  src/cuda/cuda_memory.cuh
  src/image_buffer.h
  src/memory/cpu_memory.h
  src/memory/memory_allocator.h
  src/opencl/opencl_memory.h
  test/performance_tests/performance_tests.cpp
  test/unit_tests/unit_tests.cpp
Labels: core, enhancement

#487 Add ConvertTo8Bit() SSE function implementation
  src/image_function_simd.cpp
  src/image_function_simd.h
  test/unit_tests/unit_test_image_function.cpp
Labels: enhancement, sse

#480 Optimise Dilate() function performance
  src/image_function.cpp
Labels: core, enhancement

#488 Fix compilation warnings
  examples/function_pool/example_function_pool.cpp
  src/edge_detection.cpp
  src/edge_detection.h
  src/image_function.cpp
  src/image_function_helper.cpp
  src/image_function_simd.cpp
  src/penguinv/cpu_identification.h
  src/thirdparty/kissfft/kiss_fft.c
  test/performance_tests/cuda/performance_tests_cuda.cpp
  test/performance_tests/opencl/performance_tests_opencl.cpp
  test/performance_tests/performance_test_helper.h
  test/performance_tests/performance_test_image_function.cpp
  test/performance_tests/performance_tests.cpp
  test/unit_tests/cuda/unit_tests_cuda.cpp
  test/unit_tests/opencl/unit_test_image_function_opencl.cpp
  test/unit_tests/opencl/unit_tests_opencl.cpp
  test/unit_tests/unit_test_edge_detection.cpp
  test/unit_tests/unit_test_image_function.cpp
  test/unit_tests/unit_test_math.cpp
  test/unit_tests/unit_tests.cpp
Labels: enhancement

#491 Fix for OpenCL compilation warning
  src/opencl/opencl_device.h
Labels: enhancement

#492 Disable warning for CUDA compilation
  CMakeLists.txt
Labels: enhancement

#493 Fixed chunck spelling issue
  src/cuda/cuda_memory.cuh
  src/memory/cpu_memory.h
  src/memory/memory_allocator.h
  src/opencl/opencl_memory.h
Labels: bug

#507 Add unit tests for PNG file type
  src/file/png_image.cpp
  test/unit_tests/CMakeLists.txt
  test/unit_tests/Makefile
  test/unit_tests/README.md
  test/unit_tests/unit_test_bitmap.cpp
  test/unit_tests/unit_test_png.cpp
  test/unit_tests/unit_test_png.h
  test/unit_tests/unit_tests.cpp
  test/unit_tests/unit_tests.vcxproj
Labels: enhancement, unit tests
