Repository ihhub/penguinV, pull requests merged in 2019-04, with the labels that each got.

#418 Float implementation of existing edge detection code
  examples/windows/edge_detection/main.cpp
  src/edge_detection.cpp
  src/edge_detection.h
  test/unit_tests/unit_test_edge_detection.cpp
Labels: core, enhancement

#421 Fix SSSE3 compilation if no such macro exists
  src/image_function_simd.cpp
  src/penguinv/cpu_identification.h
Labels: Linux, bug, simd, sse

#422 Histogram and projection profile visualizer class based on existing UI Window
  src/tool/ui/tool_ui.h
  src/ui/win/win_ui.cpp
Labels: New feature, gui

#423 Speed up unit tests
  test/unit_tests/unit_test_helper.cpp
Labels: enhancement, unit tests

#425 Add ConvertTo16Bit() and ConvertTo8Bit() functions
  src/image_buffer.h
  src/image_function.cpp
  src/image_function.h
Labels: core, enhancement

#433 Replace channel
  src/image_function.cpp
  src/image_function.h
  src/image_function_helper.h
  test/unit_tests/unit_test_image_function.cpp
Labels: New feature, core, unit tests

#416 Add UI Window based on X11
  examples/CMakeLists.txt
  examples/edge_detection/CMakeLists.txt
  examples/edge_detection/example_edge_detection.cpp
  examples/edge_detection/example_edge_detection.vcxproj
  examples/edge_detection/makefile
  src/ui/x11/x11_ui.cpp
  src/ui/x11/x11_ui.h
Labels: Linux, gui

#437 Parameter validation
  src/parameter_validation.h
Labels: bug, core

#439 Add unit tests for few functions
  src/filtering.cpp
  src/image_function.cpp
  src/image_function.h
  src/image_function_helper.cpp
  src/image_function_helper.h
  test/unit_tests/unit_test_image_function.cpp
Labels: core, unit tests

#440 Rename EdgeDetection and clear data before finding edge points
  examples/edge_detection/example_edge_detection.cpp
  src/edge_detection.cpp
  src/edge_detection.h
  test/unit_tests/unit_test_edge_detection.cpp
Labels: bug, core

#441 Add ROI support for Rotate function
  src/image_function.cpp
  src/image_function.h
  src/image_function_helper.cpp
  src/image_function_helper.h
Labels: core, enhancement

#442 Restructuring unit tests
  src/math/math_base.cpp
  src/math/math_base.h
  test/unit_tests/unit_test_helper.cpp
  test/unit_tests/unit_test_math.cpp
  test/unit_tests/unit_tests.cpp
Labels: math, unit tests

#445 Issue 438 - Build example_edge_detection on Linux
  examples/CMakeLists.txt
  examples/edge_detection/CMakeLists.txt
Labels: cmake, enhancement
