Repository ihhub/penguinV, pull requests merged in 2019-05, with the labels that each got.

#446 Remove duplication code in BlobInfo class
  src/blob_detection.cpp
Labels: core, enhancement

#448 add tmmintrin header file under PENGUINV_SSSE3_SET macro
  src/image_function_simd.cpp
Labels: bug, sse

#467 Change imageException to std::exception in catch block in Raspicam example
  examples/raspicam/main.cpp
Labels: enhancement

#468 Replace math.h includes with cmath
  src/cuda/filtering_cuda.cu
  src/cuda/image_function_cuda.cu
  src/filtering.cpp
  src/opencl/image_function_opencl.cpp
Labels: enhancement

#454 Complete penguinv namespace API
  src/image_function_helper.cpp
  src/image_function_helper.h
  src/penguinv/penguinv.cpp
  src/penguinv/penguinv.h
Labels: core, enhancement

#464 Issue-458: Set mfpu=neon-vfpv4 as CMake compile option
  CMakeLists.txt
Labels: cmake, enhancement

#471 Compilation warning fixes
  src/edge_detection.cpp
  src/image_function.cpp
  src/math/hough_transform.cpp
Labels: enhancement

#472 Add a support for multiple input/output images
  src/function_pool.cpp
  src/function_pool_task.cpp
  src/function_pool_task.h
Labels: core, enhancement

#473 Implement multithreaded version Split function
  doc/API_description.md
  src/function_pool.cpp
  src/function_pool.h
  test/unit_tests/unit_test_image_function.cpp
Labels: Multithreading, core

#475 Move image manager from penguinV.cpp file into common place
  src/image_function_helper.cpp
  src/image_function_helper.h
  src/penguinv/image_manager.h
  src/penguinv/penguinv.cpp
Labels: core, enhancement

#476 Disable check for a comment at the end of namespace during static analysis
  .clang-format
Labels: enhancement

#478 Add unit tests support for 16-bit images
  src/image_buffer.h
  src/image_function.cpp
  src/image_function_helper.cpp
  src/image_function_helper.h
  test/test_helper.cpp
  test/test_helper.h
  test/unit_tests/unit_test_helper.cpp
  test/unit_tests/unit_test_helper.h
  test/unit_tests/unit_test_image_function.cpp
Labels: core, enhancement, unit tests

#477 ConvertTo16Bit() SSE implementation
  src/image_function_simd.cpp
  src/image_function_simd.h
  test/unit_tests/unit_test_image_function.cpp
Labels: enhancement, simd, sse
