Repository ihhub/penguinV, pull requests merged in 2022-10, with the labels that each got.

#684 Modify examples/image_function example to use functions from penguinV namespace
  examples/image_function/CMakeLists.txt
  examples/image_function/example_image_function
  examples/image_function/example_image_function.cpp
  examples/image_function/example_image_function.vcxproj
  examples/image_function/makefile
Labels: improvement, hacktoberfest-accepted

#688 Do not use default values for input arguments
  .gitignore
  src/blob_detection.h
  src/math/math_base.h
Labels: improvement

#690 Fixed png and jpeg libraries detection for macos
  examples/file_operation/makefile
  test/unit_tests/Makefile
Labels: macOS, script

#691 added cuda examples to cmake
  CMakeLists.txt
  examples/cuda/image_function/CMakeLists.txt
  examples/cuda/pinned_memory/CMakeLists.txt
Labels: improvement, cuda, script
