Repository ihhub/penguinV, pull requests merged in 2023-11, with the labels that each got.

#695 Fix clang-format failure
  .github/workflows/github_action.yml
Labels: improvement, CI/CD

#693 Adding a cmake config to help find image resources
  CMakeLists.txt
  examples/edge_detection/CMakeLists.txt
  examples/filters/CMakeLists.txt
Labels: improvement, cmake

#696 Remove unused files
  .travis.yml
  README.md
  script/appveyor/cuda_install.cmd
  script/travis/display_log_files.sh
  script/travis/install_cuda.sh
  script/travis/install_qt5.sh
Labels: improvement, documentation
